Fix MC-123739
W-OVERFLOW/Debugify pull request #23
Opened 2022-03-29 11:39 UTC by aws404

## Description
This PR will fix MC-123739: Recipe book entries are not sorted in any meaningful manner. In fact, the order can even change randomly after a reload. 
Recipie book entries are now sorted by the ID of the first recipe in the group, leading to a consistant order in the GUI.

2022-03-29 14:39 UTC, isXander requested changes

2022-03-29 14:39 UTC, isXander commented on PATCHED.md
> +| [MC-123739](https://bugs.mojang.com/browse/MC-123739) | Recipe book entries are not sorted in any meaningful manner. In fact, the order can even change randomly after a reload.             |
please add this in alphabetical order per bug id

2022-03-29 14:39 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/client/mc123739/ClientRecipeBookMixin.java
> +    @Redirect(method = "method_30279", at = @At(value = "INVOKE", target = "Ljava/util/stream/Stream;map(Ljava/util/function/Function;)Ljava/util/stream/Stream;"))
have you tested this in forge? I had issues with lambdas in forge being remapped to mojang srgs with architectury. [see this file](https://github.com/W-OVERFLOW/Debugify/blob/1.18/common/src/main/java/cc/woverflow/debugify/mixins/client/mc234898/RealmsMainScreenMixin.java#L40)

2022-03-30 03:40 UTC, aws404 commented on common/src/main/java/cc/woverflow/debugify/mixins/client/mc123739/ClientRecipeBookMixin.java
> +    @Redirect(method = "method_30279", at = @At(value = "INVOKE", target = "Ljava/util/stream/Stream;map(Ljava/util/function/Function;)Ljava/util/stream/Stream;"))
Its working for both fabric and forge, in both Dev and Prod environements.

2022-03-30 21:00 UTC, isXander commented
Did you mean to draft this?

2022-03-31 07:06 UTC, aws404 commented
> Did you mean to draft this?

Yep, I have changed the way I went about this to reference the reload method directly rather than the lambda.

2022-03-31 07:07 UTC, merged