mc-160095 and mc-145748
W-OVERFLOW/Debugify pull request #47
Opened 2022-04-06 11:04 UTC by ThatGravyBoat

## Description

Fix 160095 by checking the block the piston is moving rather than the placeholder block.
Fix 145748 by checking if the value has changed either by dragging or clicking.

## Related Issue(s)

Fixes #19

2022-04-07 11:49 UTC, isXander requested changes

2022-04-07 11:49 UTC, isXander commented on PATCHED.md
> +| [MC-145748](https://bugs.mojang.com/browse/MC-145748) | Clicking a settings button when there's a slider under the mouse in the next screen plays the click sound twice                      |
please make this alphabetical order

2022-04-07 11:49 UTC, isXander commented on PATCHED.md
> +| [MC-160095](https://bugs.mojang.com/browse/MC-160095) | End Rods only break Cactus when moved by pistons                                                   |
please make this alphabetical order

2022-04-07 11:49 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/client/mc145748/SliderWidgetMixin.java
> +
really small but could u remove this new lines looks very ugly

2022-04-07 11:49 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/client/mc145748/SliderWidgetMixin.java
> +    private double startingValue = Double.NaN;
maybe call this `debugify$startingValue` to avoid conflicts

2022-04-07 11:49 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/client/mc145748/SliderWidgetMixin.java
> +        if (Double.isNaN(startingValue)) {
can you add javadoc explaining what this does and how it works? From looking at it this makes no sense

2022-04-07 11:49 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        slice = @Slice(
instead of using a slice, can't you just use ordinal 2?

2022-04-07 11:49 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        BlockState state = instance.getBlockState(pos);
looks like you should be using `@ModifyExpressionValue` instead of `@Redirect`

2022-04-07 12:39 UTC, ThatGravyBoat commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        BlockState state = instance.getBlockState(pos);
I used a redirect because I needed the blockpos in the world of that its checking so I could get the block entity to pull the blockstate that the pistons moving so idk if a modify express would actually work because modify express chains the previous one into the next one where as I just need the first input (BlockPos)

2022-04-07 12:41 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        BlockState state = instance.getBlockState(pos);
ur replacing the call for getBlockState and then calling that exact thing. ModifyExpression value wraps a method around the existing call and gives you that.

2022-04-07 12:47 UTC, ThatGravyBoat commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        BlockState state = instance.getBlockState(pos);
I need the blockpos that gets passed into the getblockstate here is what modifyExpression does

```java
direction = (Direction)var4.next();
BlockState blockState = this.modifyExpressionValue$zbi000$replaceBlockState(world.getBlockState(pos.offset(direction)), state, world, pos);
material = blockState.getMaterial();
```
            
Here is the redirect
            
```java
direction = (Direction)var4.next();
BlockPos injectorAllocatedLocal9 = pos.offset(direction);
BlockState blockState = this.redirect$zzj000$replaceBlockState(world, injectorAllocatedLocal9);
material = blockState.getMaterial();
```

They are very similar but the key difference is redirect gives me the original parameter modify expression doesnt.

2022-04-07 12:48 UTC, ThatGravyBoat commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        slice = @Slice(
I tried an ordinal of 2 and it decided not to go to the ordinal of 2 and went to ordinal 1 when it injected mixin out shown below where I used ordinal 2 instead of slice

```java
public boolean canPlaceAt(BlockState state, WorldView world, BlockPos pos) {
        Iterator var4 = Type.HORIZONTAL.iterator();

        Direction direction;
        Material material;
        do {
            if (!var4.hasNext()) {
                BlockState blockState2 = world.getBlockState(pos.down());
                boolean var10000;
                if (blockState2.isOf(Blocks.CACTUS) || blockState2.isOf(Blocks.SAND) || blockState2.isOf(Blocks.RED_SAND)) {
                    BlockPos injectorAllocatedLocal9 = pos.up();
                    if (!this.redirect$zbc000$replaceBlockState(world, injectorAllocatedLocal9).getMaterial().isLiquid()) {
                        var10000 = true;
                        return var10000;
                    }
                }

                var10000 = false;
                return var10000;
            }

            direction = (Direction)var4.next();
            BlockState blockState = world.getBlockState(pos.offset(direction));
            material = blockState.getMaterial();
        } while(!material.isSolid() && !world.getFluidState(pos.offset(direction)).isIn(FluidTags.LAVA));

        return false;
    }
    ```

2022-04-07 12:51 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        BlockState state = instance.getBlockState(pos);
It's okay offsetting the pos again. You can append method params to ur mixin method and get the pos and re-offset it again. Avoid Redirect at all costs!

2022-04-07 12:52 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        BlockState state = instance.getBlockState(pos);
Redirects don't stack. This will improve compat with any mod that messes with cactus

2022-04-07 13:08 UTC, ThatGravyBoat commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        BlockState state = instance.getBlockState(pos);
There must be something I'm missing because ModifyExpressionValue just doesn't seem to allow for capturing locals? which would be required to do what you are saying.

2022-04-07 13:26 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        BlockState state = instance.getBlockState(pos);
It's not a local. It's the method arguments. Just append them like an Inject

2022-04-07 13:37 UTC, ThatGravyBoat commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        BlockState state = instance.getBlockState(pos);
I must still be missing something because I tried every which way and it fails every time with the exact same error because it does not match the expected signature, even on the wiki it says "Your handler method receives the expression's resultant value (optionally followed by the enclosing method's parameters) and should return the adjusted value." where the enclosing method, in this case, is `canPlaceAt` so it receives state, world and pos not the `getBlockState` params.

2022-04-07 14:59 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        BlockState state = instance.getBlockState(pos);
https://github.com/LlamaLad7/MixinExtras/wiki/ModifyExpressionValue

2022-04-08 09:42 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc160095/CactusBlockMixin.java
> +        slice = @Slice(
This is probably because the source file is a little different to the decompiled class

2022-04-08 10:58 UTC, isXander commented
I made adjustments and implemented it in 12fc1fc

2022-04-08 10:58 UTC, closed without merging