[Build] Migrate to Quilt Mappings
W-OVERFLOW/Debugify pull request #61
Opened 2022-04-14 19:21 UTC by isXander

## Description
Yarn has come to be quite unreliable with many just wrong mappings. Migrating to Quilt could stop this.

Currently, I have backed Quilt with Mojmap as QM's completeness is quite poor.

## Concerns
The PR in its current state is quite complex due to the use of `buildSrc` this is because configuring mappings within `subprojects` does not allow for the use of `quiltMappings` or `loom.layered {}` both required to move away from yarn.

2022-04-14 19:27 UTC, isXander commented
Cannot be merged yet due to use of unreleased LoomQuiltflower with mavenLocal()

2022-04-14 19:29 UTC, MicrocontrollersDev approved these changes
I prefer QM over Yarn any day of the week. However, I cannot speak on the build.gradle changes as almost everything gradle goes straight over my head

2022-04-14 22:27 UTC, EthanDevelops requested changes
LGTM just these small fixes.

2022-04-14 22:27 UTC, EthanDevelops commented on buildSrc/build.gradle.kts
> +repositories {
Use https://repo.woverflow.cc Maven Repo as it mirrors all of these.

2022-04-14 22:27 UTC, EthanDevelops commented on buildSrc/build.gradle.kts
> +    implementation(plugin("dev.architectury.loom", "0.11.+"))
Change this to implementation(plugin("cc.woverflow.loom", "0.11.+"))

2022-04-14 22:27 UTC, EthanDevelops commented on buildSrc/build.gradle.kts
> +    implementation(plugin("io.github.juuxel.loom-quiltflower", "1.7.1"))
Change to implementation(plugin("cc.woverflow.onecoreloomplugin", "1.0.0"))

2022-04-14 22:27 UTC, EthanDevelops commented on buildSrc/src/main/kotlin/mc-setup.gradle.kts
> +    id("dev.architectury.loom")
Change to id("cc.woverflow.loom")

2022-04-14 22:27 UTC, EthanDevelops commented on buildSrc/src/main/kotlin/mc-setup.gradle.kts
> +    id("io.github.juuxel.loom-quiltflower")
Change to id(“cc.woverflow.onecoreloomplugin”)

2022-04-14 22:27 UTC, EthanDevelops commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc224729/ThreadedAnvilChunkStorageMixin.java
> +    @ModifyExpressionValue(method = "saveChunkIfNeeded(Lnet/minecraft/server/world/ChunkHolder;)Z", at = @At(value = "INVOKE", target = "Lnet/minecraft/server/world/ChunkHolder;isAccessible()Z"))
You don’t need to use the full mapping path iirc.

2022-04-14 22:28 UTC, EthanDevelops commented on buildSrc/src/main/kotlin/mc-setup.gradle.kts
> +    id("io.github.juuxel.loom-quiltflower")
If you have problems with it just dm me and you can use current for now.

2022-04-15 06:42 UTC, isXander commented on buildSrc/build.gradle.kts
> +repositories {
I believe it's more clear to explicitly use the repos rather than using an implicit mirror.

2022-04-15 06:49 UTC, isXander commented on buildSrc/build.gradle.kts
> +    implementation(plugin("dev.architectury.loom", "0.11.+"))
Does this add anything beside FG2 support ported to 0.11?

2022-04-15 06:50 UTC, isXander commented on buildSrc/build.gradle.kts
> +    implementation(plugin("io.github.juuxel.loom-quiltflower", "1.7.1"))
base LQF is fine and I don't really want onecore support?

2022-04-15 06:51 UTC, isXander commented on buildSrc/build.gradle.kts
> +    implementation(plugin("io.github.juuxel.loom-quiltflower", "1.7.1"))
Also, this hasn't been fetched recently and has a breaking bug that 1.7.1 fixed.

2022-04-15 07:03 UTC, isXander commented on common/src/main/java/cc/woverflow/debugify/mixins/server/mc224729/ThreadedAnvilChunkStorageMixin.java
> +    @ModifyExpressionValue(method = "saveChunkIfNeeded(Lnet/minecraft/server/world/ChunkHolder;)Z", at = @At(value = "INVOKE", target = "Lnet/minecraft/server/world/ChunkHolder;isAccessible()Z"))
oh yeah, got it

2022-04-15 07:07 UTC, isXander commented
I am going to merge despite the requested changes as it doesn't actually apply to the PR but the project itself. It can be changed later.

2022-04-15 07:17 UTC, merged